### ISSUE TITLE
Fly Voucher

### ISSUE THREAD

**Issue by ExecutableJarFile** [PrisonReimagined/Suggestions#14]
**Feature Request**
For the _**/fly**_ command reward from crates, I think once a player has fly via permission or a rank, they can get a redeemable item that once used, grants fly. This will allow players to gift/sell these via AH to other players. So even if you got fly, you can earn something from selling it/trading it, instead of it being a wasted key.

**Comment by mccormack-harry** [comment]
If you already have the permission for a permission reward, you can't win the reward.
So you can't win fly twice.
